#ifndef SOURCE_READER_APPLICATION_APP_INCLUDE_COMMUNICATION_STACK_SERVICE_SERVICE_TYPES
#define SOURCE_READER_APPLICATION_APP_INCLUDE_COMMUNICATION_STACK_SERVICE_SERVICE_TYPES

#ifdef __cplusplus
extern "C" {
#endif

typedef enum ServiceType
{
    SERVICE_TYPE__N_ELEMENTS

} ServiceType;

#ifdef __cplusplus
}
#endif

#endif